### ISSUE TITLE
Mod Crashing on servers

### ISSUE THREAD

**Issue by Bright1337** [Matyrobbrt/FireNetherite#1] opened 2021-08-30 10:13 UTC
java.lang.NoSuchMethodError: 'net.minecraft.item.ItemStack net.minecraft.entity.player.PlayerInventory.func_70440_f(int)'
	at com.matyrobbrt.firenetherite.common.events.PlayerEvents.netheriteArmourFireResistance(PlayerEvents.java:29) ~[firenetherite:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_96_PlayerEvents_netheriteArmourFireResistance_PlayerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:97) ~[forge:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:224) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enderitemod.mixins.json:ElytraPlayerEntityMixin,pl:mixin:APP:enderitemod.mixins.json:EnderiteRespawnAnchorMixin,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:vampirism.mixins.json:MixinPlayerEntity,pl:mixin:APP:netherite_plus.mixins.json:PlayerEntityMixin,pl:mixin:APP:multi-item-lib.mixins.json:PlayerEntityMixin,pl:mixin:APP:attackspeedenchantment.mixins.json:PlayerEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:APP:imm_ptl_mixins.json:common.block_manipulation.MixinPlayerEntity_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:527) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:advancement.ServerPlayerEntityMixin,pl:mixin:APP:imm_ptl_mixins.json:common.chunk_sync.MixinServerPlayerEntity,pl:mixin:APP:imm_ptl_mixins.json:common.entity_sync.MixinServerPlayerEntity,pl:mixin:APP:imm_ptl_mixins_forge.json:common.MixinServerPlayerEntity_MA,pl:mixin:APP:performant.mixins.json:entity.ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:403) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerList,pl:mixin:APP:imm_ptl_mixins.json:common.MixinPlayerManager,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinPlayerManager_P,pl:mixin:APP:imm_ptl_mixins_forge.json:common.MixinPlayerManager_MA,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.management.PlayerList.disconnect(PlayerList.java:386) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerList,pl:mixin:APP:imm_ptl_mixins.json:common.MixinPlayerManager,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinPlayerManager_P,pl:mixin:APP:imm_ptl_mixins_forge.json:common.MixinPlayerManager_MA,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147231_a(ServerPlayNetHandler.java:1534) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:connection.ServerPlayNetHandlerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.position_sync.MixinServerPlayNetworkHandler,pl:mixin:APP:netherite_plus.mixins.json:ServerPlayNetworkHandlerMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ServerPlayNetHandlerAccess,pl:mixin:APP:imm_ptl_mixins.json:common.entity_sync.MixinServerPlayNetworkHandler_E,pl:mixin:A}
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:387) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:161) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1055) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:945) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:760) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:829) [?:?] {}

**Comment by Matyrobbrt** [comment] 2021-09-16 07:57
Version? 1.16 or 1.17

**Comment by Matyrobbrt** [comment] 2021-09-19 18:11
@Bright1337 this should be fixed in the next update. But I can't test it on a server so I will have to hope it works

**Comment by Matyrobbrt** [comment] 2021-12-12 15:22
@Bright1337 Sorry for the long wait, i was working on some other big projects. The issue is now fixed: https://www.curseforge.com/minecraft/mc-mods/fire-netherite/files/3562564
Thank you for reporting it!

**Closed as completed by Matyrobbrt** 2021-12-12 15:22 UTC
